"""add student face data table for exam verification

Revision ID: 28c2fd37876a
Revises: bde1207b1377
Create Date: 2025-11-13 15:43:44.923166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28c2fd37876a'
down_revision: Union[str, None] = 'bde1207b1377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_face_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('enrollment_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('confidence_score', sa.String(), nullable=True),
    sa.Column('image_quality', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_face_data_id'), 'student_face_data', ['id'], unique=False)
    op.create_index(op.f('ix_student_face_data_user_id'), 'student_face_data', ['user_id'], unique=False)
    op.drop_index('ix_parent_students_id', table_name='parent_students')
    op.drop_index('ix_parent_students_parent_id', table_name='parent_students')
    op.drop_index('ix_parent_students_student_id', table_name='parent_students')
    op.drop_table('parent_students')
    op.drop_index('ix_ai_usage_events_created_at', table_name='ai_usage_events')
    op.drop_index('ix_ai_usage_events_feature', table_name='ai_usage_events')
    op.drop_index('ix_ai_usage_events_id', table_name='ai_usage_events')
    op.drop_index('ix_ai_usage_events_user_id', table_name='ai_usage_events')
    op.drop_index('ix_ai_usage_feature_created_at', table_name='ai_usage_events')
    op.drop_index('ix_ai_usage_user_created_at', table_name='ai_usage_events')
    op.drop_table('ai_usage_events')
    op.alter_column('exercise_submissions', 'grading_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('exercise_submissions', 'teacher_reviewed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_submission_grading_status', table_name='exercise_submissions')
    op.drop_index('idx_submission_queue_position', table_name='exercise_submissions')
    op.create_index('idx_submission_date_range', 'exercise_submissions', ['submitted_at', 'exercise_id'], unique=False)
    op.create_index('idx_submission_graded', 'exercise_submissions', ['graded_at', 'score'], unique=False)
    op.create_index('idx_submission_student_exercise', 'exercise_submissions', ['student_id', 'exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_submissions_graded_at'), 'exercise_submissions', ['graded_at'], unique=False)
    op.create_index(op.f('ix_exercise_submissions_grading_status'), 'exercise_submissions', ['grading_status'], unique=False)
    op.create_index(op.f('ix_exercise_submissions_score'), 'exercise_submissions', ['score'], unique=False)
    op.create_index(op.f('ix_exercise_submissions_status'), 'exercise_submissions', ['status'], unique=False)
    op.create_index(op.f('ix_exercise_submissions_submitted_at'), 'exercise_submissions', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_exercise_submissions_teacher_reviewed'), 'exercise_submissions', ['teacher_reviewed'], unique=False)
    op.drop_constraint('exercise_submissions_teacher_reviewed_by_fkey', 'exercise_submissions', type_='foreignkey')
    op.drop_column('exercise_submissions', 'original_ai_score')
    op.drop_column('exercise_submissions', 'teacher_reviewed_by')
    op.drop_column('exercise_submissions', 'teacher_reviewed_at')
    op.drop_column('exercise_submissions', 'teacher_notes')
    op.create_index('idx_exercise_class_created', 'exercises', ['class_id', 'created_at'], unique=False)
    op.create_index('idx_exercise_class_skill', 'exercises', ['class_id', 'skill_type'], unique=False)
    op.create_index(op.f('ix_exercises_created_at'), 'exercises', ['created_at'], unique=False)
    op.create_index(op.f('ix_exercises_due_at'), 'exercises', ['due_at'], unique=False)
    op.create_index(op.f('ix_exercises_skill_type'), 'exercises', ['skill_type'], unique=False)
    op.create_index(op.f('ix_exercises_type'), 'exercises', ['type'], unique=False)
    op.add_column('notifications', sa.Column('related_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('related_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'related_type')
    op.drop_column('notifications', 'related_id')
    op.drop_index(op.f('ix_exercises_type'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_skill_type'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_due_at'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_created_at'), table_name='exercises')
    op.drop_index('idx_exercise_class_skill', table_name='exercises')
    op.drop_index('idx_exercise_class_created', table_name='exercises')
    op.add_column('exercise_submissions', sa.Column('teacher_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('exercise_submissions', sa.Column('teacher_reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('exercise_submissions', sa.Column('teacher_reviewed_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exercise_submissions', sa.Column('original_ai_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_foreign_key('exercise_submissions_teacher_reviewed_by_fkey', 'exercise_submissions', 'users', ['teacher_reviewed_by'], ['id'])
    op.drop_index(op.f('ix_exercise_submissions_teacher_reviewed'), table_name='exercise_submissions')
    op.drop_index(op.f('ix_exercise_submissions_submitted_at'), table_name='exercise_submissions')
    op.drop_index(op.f('ix_exercise_submissions_status'), table_name='exercise_submissions')
    op.drop_index(op.f('ix_exercise_submissions_score'), table_name='exercise_submissions')
    op.drop_index(op.f('ix_exercise_submissions_grading_status'), table_name='exercise_submissions')
    op.drop_index(op.f('ix_exercise_submissions_graded_at'), table_name='exercise_submissions')
    op.drop_index('idx_submission_student_exercise', table_name='exercise_submissions')
    op.drop_index('idx_submission_graded', table_name='exercise_submissions')
    op.drop_index('idx_submission_date_range', table_name='exercise_submissions')
    op.create_index('idx_submission_queue_position', 'exercise_submissions', ['queue_position'], unique=False)
    op.create_index('idx_submission_grading_status', 'exercise_submissions', ['grading_status'], unique=False)
    op.alter_column('exercise_submissions', 'teacher_reviewed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('exercise_submissions', 'grading_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_table('ai_usage_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feature', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('metadata_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='ai_usage_events_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ai_usage_events_pkey')
    )
    op.create_index('ix_ai_usage_user_created_at', 'ai_usage_events', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_ai_usage_feature_created_at', 'ai_usage_events', ['feature', 'created_at'], unique=False)
    op.create_index('ix_ai_usage_events_user_id', 'ai_usage_events', ['user_id'], unique=False)
    op.create_index('ix_ai_usage_events_id', 'ai_usage_events', ['id'], unique=False)
    op.create_index('ix_ai_usage_events_feature', 'ai_usage_events', ['feature'], unique=False)
    op.create_index('ix_ai_usage_events_created_at', 'ai_usage_events', ['created_at'], unique=False)
    op.create_table('parent_students',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], name='parent_students_parent_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='parent_students_student_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='parent_students_pkey'),
    sa.UniqueConstraint('parent_id', 'student_id', name='uq_parent_student')
    )
    op.create_index('ix_parent_students_student_id', 'parent_students', ['student_id'], unique=False)
    op.create_index('ix_parent_students_parent_id', 'parent_students', ['parent_id'], unique=False)
    op.create_index('ix_parent_students_id', 'parent_students', ['id'], unique=False)
    op.drop_index(op.f('ix_student_face_data_user_id'), table_name='student_face_data')
    op.drop_index(op.f('ix_student_face_data_id'), table_name='student_face_data')
    op.drop_table('student_face_data')
    # ### end Alembic commands ###
