"""add_progress_to_video_lesson

Revision ID: c58aa4805da0
Revises: 018_add_video_lessons
Create Date: 2025-11-22 09:28:40.334747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c58aa4805da0'
down_revision: Union[str, None] = '018_add_video_lessons'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_lessons', sa.Column('progress', sa.Integer(), nullable=True, default=0))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_lessons', 'progress')
    # ### end Alembic commands ###
