"""add_class_id_to_video_lessons

Revision ID: f03ec8df5a70
Revises: c58aa4805da0
Create Date: 2025-11-22 10:59:10.937412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f03ec8df5a70'
down_revision: Union[str, None] = 'c58aa4805da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_usage_events_created_at', table_name='ai_usage_events')
    op.drop_index('ix_ai_usage_events_feature', table_name='ai_usage_events')
    op.drop_index('ix_ai_usage_events_id', table_name='ai_usage_events')
    op.drop_index('ix_ai_usage_events_user_id', table_name='ai_usage_events')
    op.drop_index('ix_ai_usage_feature_created_at', table_name='ai_usage_events')
    op.drop_index('ix_ai_usage_user_created_at', table_name='ai_usage_events')
    op.drop_table('ai_usage_events')
    op.drop_index('ix_parent_students_id', table_name='parent_students')
    op.drop_index('ix_parent_students_parent_id', table_name='parent_students')
    op.drop_index('ix_parent_students_student_id', table_name='parent_students')
    op.drop_table('parent_students')
    op.drop_index('idx_submission_graded_at', table_name='exercise_submissions')
    op.drop_index('idx_submission_score', table_name='exercise_submissions')
    op.drop_index('idx_submission_status', table_name='exercise_submissions')
    op.drop_index('idx_submission_submitted_at', table_name='exercise_submissions')
    op.drop_index('idx_submissions_review_pending', table_name='exercise_submissions')
    op.drop_index('ix_submissions_grading_status', table_name='exercise_submissions')
    op.drop_index('ix_submissions_teacher_reviewed', table_name='exercise_submissions')
    op.drop_constraint('fk_submission_teacher_reviewed_by', 'exercise_submissions', type_='foreignkey')
    op.drop_column('exercise_submissions', 'teacher_reviewed_by')
    op.drop_column('exercise_submissions', 'teacher_reviewed_at')
    op.drop_column('exercise_submissions', 'teacher_notes')
    op.drop_column('exercise_submissions', 'original_ai_score')
    op.drop_index('idx_exercise_created_at', table_name='exercises')
    op.drop_index('idx_exercise_due_at', table_name='exercises')
    op.drop_index('idx_exercise_skill_type', table_name='exercises')
    op.drop_index('idx_exercise_type', table_name='exercises')
    op.add_column('video_lessons', sa.Column('class_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_video_lessons_class_id'), 'video_lessons', ['class_id'], unique=False)
    op.create_foreign_key(None, 'video_lessons', 'classes', ['class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video_lessons', type_='foreignkey')
    op.drop_index(op.f('ix_video_lessons_class_id'), table_name='video_lessons')
    op.drop_column('video_lessons', 'class_id')
    op.create_index('idx_exercise_type', 'exercises', ['type'], unique=False)
    op.create_index('idx_exercise_skill_type', 'exercises', ['skill_type'], unique=False)
    op.create_index('idx_exercise_due_at', 'exercises', ['due_at'], unique=False)
    op.create_index('idx_exercise_created_at', 'exercises', ['created_at'], unique=False)
    op.add_column('exercise_submissions', sa.Column('original_ai_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('exercise_submissions', sa.Column('teacher_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('exercise_submissions', sa.Column('teacher_reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('exercise_submissions', sa.Column('teacher_reviewed_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_submission_teacher_reviewed_by', 'exercise_submissions', 'users', ['teacher_reviewed_by'], ['id'], ondelete='SET NULL')
    op.create_index('ix_submissions_teacher_reviewed', 'exercise_submissions', ['teacher_reviewed'], unique=False)
    op.create_index('ix_submissions_grading_status', 'exercise_submissions', ['grading_status'], unique=False)
    op.create_index('idx_submissions_review_pending', 'exercise_submissions', ['grading_status', 'teacher_reviewed', 'submitted_at'], unique=False)
    op.create_index('idx_submission_submitted_at', 'exercise_submissions', ['submitted_at'], unique=False)
    op.create_index('idx_submission_status', 'exercise_submissions', ['status'], unique=False)
    op.create_index('idx_submission_score', 'exercise_submissions', ['score'], unique=False)
    op.create_index('idx_submission_graded_at', 'exercise_submissions', ['graded_at'], unique=False)
    op.create_table('parent_students',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], name='parent_students_parent_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='parent_students_student_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='parent_students_pkey'),
    sa.UniqueConstraint('parent_id', 'student_id', name='uq_parent_student')
    )
    op.create_index('ix_parent_students_student_id', 'parent_students', ['student_id'], unique=False)
    op.create_index('ix_parent_students_parent_id', 'parent_students', ['parent_id'], unique=False)
    op.create_index('ix_parent_students_id', 'parent_students', ['id'], unique=False)
    op.create_table('ai_usage_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feature', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('metadata_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='ai_usage_events_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ai_usage_events_pkey')
    )
    op.create_index('ix_ai_usage_user_created_at', 'ai_usage_events', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_ai_usage_feature_created_at', 'ai_usage_events', ['feature', 'created_at'], unique=False)
    op.create_index('ix_ai_usage_events_user_id', 'ai_usage_events', ['user_id'], unique=False)
    op.create_index('ix_ai_usage_events_id', 'ai_usage_events', ['id'], unique=False)
    op.create_index('ix_ai_usage_events_feature', 'ai_usage_events', ['feature'], unique=False)
    op.create_index('ix_ai_usage_events_created_at', 'ai_usage_events', ['created_at'], unique=False)
    # ### end Alembic commands ###
