"""add_exercise_submission_support_to_proctoring

Revision ID: f9d5a7450324
Revises: c9f87988d34a
Create Date: 2025-11-15 08:46:46.013712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9d5a7450324'
down_revision: Union[str, None] = 'c9f87988d34a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_usage_events_created_at', table_name='ai_usage_events')
    op.drop_index('ix_ai_usage_events_feature', table_name='ai_usage_events')
    op.drop_index('ix_ai_usage_events_id', table_name='ai_usage_events')
    op.drop_index('ix_ai_usage_events_user_id', table_name='ai_usage_events')
    op.drop_index('ix_ai_usage_feature_created_at', table_name='ai_usage_events')
    op.drop_index('ix_ai_usage_user_created_at', table_name='ai_usage_events')
    op.drop_table('ai_usage_events')
    op.drop_index('ix_parent_students_id', table_name='parent_students')
    op.drop_index('ix_parent_students_parent_id', table_name='parent_students')
    op.drop_index('ix_parent_students_student_id', table_name='parent_students')
    op.drop_table('parent_students')
    op.add_column('exam_monitoring_sessions', sa.Column('exercise_submission_id', sa.Integer(), nullable=True))
    op.alter_column('exam_monitoring_sessions', 'submission_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_exam_monitoring_sessions_submission_id', table_name='exam_monitoring_sessions')
    op.create_index(op.f('ix_exam_monitoring_sessions_submission_id'), 'exam_monitoring_sessions', ['submission_id'], unique=False)
    op.create_index(op.f('ix_exam_monitoring_sessions_exercise_submission_id'), 'exam_monitoring_sessions', ['exercise_submission_id'], unique=False)
    op.create_foreign_key(None, 'exam_monitoring_sessions', 'exercise_submissions', ['exercise_submission_id'], ['id'])
    op.add_column('exam_proctoring_logs', sa.Column('exercise_submission_id', sa.Integer(), nullable=True))
    op.alter_column('exam_proctoring_logs', 'submission_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_exam_proctoring_logs_exercise_submission_id'), 'exam_proctoring_logs', ['exercise_submission_id'], unique=False)
    op.create_foreign_key(None, 'exam_proctoring_logs', 'exercise_submissions', ['exercise_submission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exam_proctoring_logs', type_='foreignkey')
    op.drop_index(op.f('ix_exam_proctoring_logs_exercise_submission_id'), table_name='exam_proctoring_logs')
    op.alter_column('exam_proctoring_logs', 'submission_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('exam_proctoring_logs', 'exercise_submission_id')
    op.drop_constraint(None, 'exam_monitoring_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_exam_monitoring_sessions_exercise_submission_id'), table_name='exam_monitoring_sessions')
    op.drop_index(op.f('ix_exam_monitoring_sessions_submission_id'), table_name='exam_monitoring_sessions')
    op.create_index('ix_exam_monitoring_sessions_submission_id', 'exam_monitoring_sessions', ['submission_id'], unique=False)
    op.alter_column('exam_monitoring_sessions', 'submission_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('exam_monitoring_sessions', 'exercise_submission_id')
    op.create_table('parent_students',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], name='parent_students_parent_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='parent_students_student_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='parent_students_pkey'),
    sa.UniqueConstraint('parent_id', 'student_id', name='uq_parent_student')
    )
    op.create_index('ix_parent_students_student_id', 'parent_students', ['student_id'], unique=False)
    op.create_index('ix_parent_students_parent_id', 'parent_students', ['parent_id'], unique=False)
    op.create_index('ix_parent_students_id', 'parent_students', ['id'], unique=False)
    op.create_table('ai_usage_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feature', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('metadata_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='ai_usage_events_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ai_usage_events_pkey')
    )
    op.create_index('ix_ai_usage_user_created_at', 'ai_usage_events', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_ai_usage_feature_created_at', 'ai_usage_events', ['feature', 'created_at'], unique=False)
    op.create_index('ix_ai_usage_events_user_id', 'ai_usage_events', ['user_id'], unique=False)
    op.create_index('ix_ai_usage_events_id', 'ai_usage_events', ['id'], unique=False)
    op.create_index('ix_ai_usage_events_feature', 'ai_usage_events', ['feature'], unique=False)
    op.create_index('ix_ai_usage_events_created_at', 'ai_usage_events', ['created_at'], unique=False)
    # ### end Alembic commands ###
